### ISSUE TITLE
Can't render PDF

### ISSUE THREAD

**Issue by MoemenMostafa** [vernes/PHPReport#2]
when I render PDF i got the following error in the generated PDF file (when opening it with text editor)

<br />
<b>Fatal error</b>:  Uncaught exception 'PHPExcel_Writer_Exception' with message 'PDF Rendering library has not been defined.' in D:\xampp\htdocs\php_report\PHPExcel-develop\Classes\PHPExcel\Writer\PDF.php:51
Stack trace:
#0 D:\xampp\htdocs\php_report\PHPExcel-develop\Classes\PHPExcel\IOFactory.php(141): PHPExcel_Writer_PDF-&gt;__construct(Object(PHPExcel))
#1 D:\xampp\htdocs\php_report\PHPReport.php(980): PHPExcel_IOFactory::createWriter(Object(PHPExcel), 'PDF')
#2 D:\xampp\htdocs\php_report\PHPReport.php(906): PHPReport-&gt;renderPdf('Report 2012-12-...')
#3 D:\xampp\htdocs\php_report\examples\example_9.php(58): PHPReport-&gt;render('pdf')
#4 {main}

  thrown in <b>D:\xampp\htdocs\php_report\PHPExcel-develop\Classes\PHPExcel\Writer\PDF.php</b> on line <b>51</b><br />

Could you please help me in this issue?

**Comment by sumitguptamca** [comment]
when I render PDF i got the following error in the generated PDF file 
<br />
<b>Fatal error</b>:  Uncaught PHPExcel_Writer_Exception: PDF Rendering library has not been defined. in D:\XAMPP\htdocs\shinchuo\php-report\vendor\phpoffice\phpexcel\Classes\PHPExcel\Writer\PDF.php:48
Stack trace:
#0 D:\XAMPP\htdocs\shinchuo\php-report\vendor\phpoffice\phpexcel\Classes\PHPExcel\IOFactory.php(139): PHPExcel_Writer_PDF-&gt;__construct(Object(PHPExcel))
#1 D:\XAMPP\htdocs\shinchuo\php-report\PHPReport_pf.php(1007): PHPExcel_IOFactory::createWriter(Object(PHPExcel), 'PDF')
#2 D:\XAMPP\htdocs\shinchuo\php-report\PHPReport_pf.php(931): PHPReport-&gt;renderPdf('pf_invoice2021-...')
#3 D:\XAMPP\htdocs\shinchuo\admin\pf_invoice_excel.php(91): PHPReport-&gt;render('PDF')
#4 {main}
  thrown in <b>D:\XAMPP\htdocs\shinchuo\php-report\vendor\phpoffice\phpexcel\Classes\PHPExcel\Writer\PDF.php</b> on line <b>48</b><br />
